# Generated by Django 4.1 on 2023-06-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="board_id", new_name="board",
        ),
    ]
