# Generated by Django 4.1 on 2023-06-07 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_rename_board_id_comment_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "최소 10글자 이상은 입력해주셔야 합니다."
                    )
                ],
                verbose_name="내용",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "최소 3글자 이상은 입력해주셔야합니다."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "최소 3글자 이상은 입력해주셔야합니다."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
