# Generated by Django 4.1 on 2023-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_board_content_alter_board_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
