# Generated by Django 4.1 on 2023-06-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Toon",
            fields=[
                ("titleid", models.AutoField(primary_key=True, serialize=False)),
                ("titlename", models.CharField(max_length=50)),
                (
                    "starscore",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("startdate", models.DateTimeField(auto_now_add=True)),
                ("genre", models.CharField(max_length=100, null=True)),
                ("thumnail_URL", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="toon.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment", models.CharField(max_length=256, null=True)),
                ("commentid", models.AutoField(primary_key=True, serialize=False)),
                ("like", models.IntegerField(null=True)),
                (
                    "toon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="toon.toon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="toon.user",
                    ),
                ),
            ],
        ),
    ]
