# Generated by Django 4.1 on 2023-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toon",
            name="titleid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
