# Generated by Django 4.1 on 2023-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toon", "0003_alter_toon_titleid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="comment", field=models.TextField(null=True),
        ),
    ]
