# Generated by Django 4.1 on 2023-06-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toon", "0004_alter_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="toon",
            name="user",
            field=models.ManyToManyField(through="toon.Comment", to="toon.user"),
        ),
    ]
